# Generated by Django 4.2.7 on 2023-11-19 10:50

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("social_media", "0002_remove_post_images_image_post"),
    ]

    operations = [
        migrations.RenameField(
            model_name="post",
            old_name="content",
            new_name="contend",
        ),
    ]
