# Generated by Django 4.2.7 on 2023-11-20 17:57

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("social_media", "0004_tag_comment_post_post_tags"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="tag",
            options={"ordering": ["name"]},
        ),
        migrations.AlterField(
            model_name="post",
            name="tags",
            field=models.ManyToManyField(
                blank=True,
                null=True,
                related_name="posts",
                to="social_media.tag",
            ),
        ),
    ]
