# Generated by Django 4.2.7 on 2023-11-21 13:39

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("social_media", "0005_alter_tag_options_alter_post_tags"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="post",
            options={"ordering": ["-created_at"]},
        ),
        migrations.AlterField(
            model_name="post",
            name="tags",
            field=models.ManyToManyField(
                blank=True, related_name="posts", to="social_media.tag"
            ),
        ),
    ]
